"""
拼音音节词典和常用词库
Pinyin syllable dictionary and common word mappings.
"""

# 所有合法的拼音音节 (不带声调)
PY_SYLLABLES = {
    # a 系
    "a", "ai", "an", "ang", "ao",
    # b 系
    "ba", "bai", "ban", "bang", "bao", "bei", "ben", "beng", "bi", "bian",
    "biao", "bie", "bin", "bing", "bo", "bu",
    # c 系
    "ca", "cai", "can", "cang", "cao", "ce", "cen", "ceng", "cha", "chai",
    "chan", "chang", "chao", "che", "chen", "cheng", "chi", "chong", "chou",
    "chu", "chuai", "chuan", "chuang", "chui", "chun", "chuo", "ci", "cong",
    "cou", "cu", "cuan", "cui", "cun", "cuo",
    # d 系
    "da", "dai", "dan", "dang", "dao", "de", "dei", "den", "deng", "di",
    "dian", "diao", "die", "ding", "diu", "dong", "dou", "du", "duan",
    "dui", "dun", "duo",
    # e 系
    "e", "ei", "en", "eng", "er",
    # f 系
    "fa", "fan", "fang", "fei", "fen", "feng", "fo", "fou", "fu",
    # g 系
    "ga", "gai", "gan", "gang", "gao", "ge", "gei", "gen", "geng", "gong",
    "gou", "gu", "gua", "guai", "guan", "guang", "gui", "gun", "guo",
    # h 系
    "ha", "hai", "han", "hang", "hao", "he", "hei", "hen", "heng", "hong",
    "hou", "hu", "hua", "huai", "huan", "huang", "hui", "hun", "huo",
    # j 系
    "ji", "jia", "jian", "jiang", "jiao", "jie", "jin", "jing", "jiong",
    "jiu", "ju", "juan", "jue", "jun",
    # k 系
    "ka", "kai", "kan", "kang", "kao", "ke", "kei", "ken", "keng", "kong",
    "kou", "ku", "kua", "kuai", "kuan", "kuang", "kui", "kun", "kuo",
    # l 系
    "la", "lai", "lan", "lang", "lao", "le", "lei", "leng", "li", "lia",
    "lian", "liang", "liao", "lie", "lin", "ling", "liu", "long", "lou",
    "lu", "luan", "lun", "luo", "lv", "lve",
    # m 系
    "ma", "mai", "man", "mang", "mao", "me", "mei", "men", "meng", "mi",
    "mian", "miao", "mie", "min", "ming", "miu", "mo", "mou", "mu",
    # n 系
    "na", "nai", "nan", "nang", "nao", "ne", "nei", "nen", "neng", "ni",
    "nian", "niang", "niao", "nie", "nin", "ning", "niu", "nong", "nou",
    "nu", "nuan", "nuo", "nv", "nve",
    # o 系
    "o", "ou",
    # p 系
    "pa", "pai", "pan", "pang", "pao", "pei", "pen", "peng", "pi", "pian",
    "piao", "pie", "pin", "ping", "po", "pou", "pu",
    # q 系
    "qi", "qia", "qian", "qiang", "qiao", "qie", "qin", "qing", "qiong",
    "qiu", "qu", "quan", "que", "qun",
    # r 系
    "ran", "rang", "rao", "re", "ren", "reng", "ri", "rong", "rou", "ru",
    "ruan", "rui", "run", "ruo",
    # s 系
    "sa", "sai", "san", "sang", "sao", "se", "sen", "seng", "sha", "shai",
    "shan", "shang", "shao", "she", "shei", "shen", "sheng", "shi", "shou",
    "shu", "shua", "shuai", "shuan", "shuang", "shui", "shun", "shuo", "si",
    "song", "sou", "su", "suan", "sui", "sun", "suo",
    # t 系
    "ta", "tai", "tan", "tang", "tao", "te", "teng", "ti", "tian", "tiao",
    "tie", "ting", "tong", "tou", "tu", "tuan", "tui", "tun", "tuo",
    # w 系
    "wa", "wai", "wan", "wang", "wei", "wen", "weng", "wo", "wu",
    # x 系
    "xi", "xia", "xian", "xiang", "xiao", "xie", "xin", "xing", "xiong",
    "xiu", "xu", "xuan", "xue", "xun",
    # y 系
    "ya", "yan", "yang", "yao", "ye", "yi", "yin", "ying", "yo", "yong",
    "you", "yu", "yuan", "yue", "yun",
    # z 系
    "za", "zai", "zan", "zang", "zao", "ze", "zei", "zen", "zeng", "zha",
    "zhai", "zhan", "zhang", "zhao", "zhe", "zhei", "zhen", "zheng", "zhi",
    "zhong", "zhou", "zhu", "zhua", "zhuai", "zhuan", "zhuang", "zhui",
    "zhun", "zhuo", "zi", "zong", "zou", "zu", "zuan", "zui", "zun", "zuo",
}

# 常用词库: pinyin字符串 -> [中文候选词列表]
# 按词频排序，越常用越靠前
WORD_DICT = {
    # 单字高频词
    "wo": ["我"],
    "ni": ["你"],
    "ta": ["他", "她", "它"],
    "shi": ["是", "事", "十", "时", "使", "市", "室", "式"],
    "de": ["的", "得", "地", "德"],
    "le": ["了", "乐"],
    "bu": ["不", "部", "步", "布"],
    "zai": ["在", "再"],
    "you": ["有", "又", "由", "友", "右", "游"],
    "ren": ["人", "认", "任", "忍"],
    "zhe": ["这", "着"],
    "he": ["和", "合", "何", "河"],
    "da": ["大", "打", "答", "达"],
    "lai": ["来"],
    "qu": ["去", "取", "趣"],
    "shang": ["上", "商", "伤"],
    "xia": ["下", "夏", "吓"],
    "zhong": ["中", "种", "重", "钟"],
    "guo": ["国", "过", "果", "郭"],
    "ge": ["个", "各", "哥", "歌"],
    "men": ["们", "门"],
    "yao": ["要", "药", "摇", "腰"],
    "neng": ["能"],
    "hui": ["会", "回", "惠", "辉"],
    "ke": ["可", "科", "克", "客", "课"],
    "yi": ["一", "以", "已", "意", "义", "亿", "易"],
    "jiu": ["就", "九", "久", "酒", "旧", "救"],
    "xian": ["先", "现", "线", "限", "显", "县", "险"],
    "jin": ["进", "今", "近", "金", "尽", "紧"],
    "tian": ["天", "田", "填", "甜"],
    "ri": ["日"],
    "xin": ["心", "新", "信", "辛"],
    "sheng": ["生", "声", "省", "升", "胜"],
    "ming": ["明", "名", "命", "鸣"],
    "xiao": ["小", "笑", "消", "效", "校"],
    "chang": ["长", "常", "场", "厂", "唱"],
    "duo": ["多", "夺", "朵"],
    "shou": ["手", "受", "收", "首", "守"],
    "gan": ["感", "干", "敢", "赶"],
    "zhi": ["知", "只", "之", "制", "直", "至", "指"],
    "dao": ["到", "道", "倒", "岛", "导"],
    "kan": ["看", "砍"],
    "jian": ["见", "件", "间", "建", "简", "健"],
    "wen": ["文", "问", "闻", "温"],
    "dong": ["动", "东", "懂", "冬", "洞"],
    "fang": ["方", "放", "房", "访"],
    "xiang": ["想", "向", "像", "象", "相", "项", "香"],
    "hao": ["好", "号", "毫", "浩"],
    "mei": ["没", "每", "美", "妹", "媒"],
    "shui": ["水", "谁", "睡", "税"],
    "kuai": ["快", "块", "筷"],
    "man": ["慢", "满", "蛮"],
    "nan": ["难", "男", "南"],
    "nv": ["女"],
    "er": ["而", "二", "儿", "耳"],
    "tong": ["同", "通", "痛", "童", "统"],
    "hua": ["话", "化", "花", "画", "华"],
    "dian": ["点", "电", "店", "典"],
    "zuo": ["做", "作", "坐", "左", "昨"],
    "shuo": ["说"],
    "xie": ["写", "谢", "些", "协", "鞋"],
    "jia": ["家", "加", "假", "价", "架"],
    "xue": ["学", "血", "雪", "薛"],
    "chi": ["吃", "尺"],
    "he": ["喝", "和", "合", "何"],
    "wan": ["万", "完", "玩", "晚", "碗"],
    "qing": ["请", "情", "清", "轻", "青"],
    "gao": ["高", "告", "搞"],
    "zou": ["走", "奏"],
    "suo": ["所", "索", "锁"],
    "ru": ["如", "入", "儒"],
    "si": ["四", "死", "思", "丝", "私"],
    "wu": ["五", "无", "物", "务", "误", "屋"],
    "qi": ["七", "起", "其", "期", "气", "奇"],
    "ba": ["八", "吧", "把", "爸", "巴"],
    "ji": ["几", "机", "记", "及", "级", "极", "集", "急"],
    "li": ["里", "理", "力", "利", "立", "李"],
    "chu": ["出", "处", "初", "除", "楚", "础"],
    "kai": ["开", "凯"],
    "guan": ["关", "管", "观", "官", "馆"],
    "zhu": ["主", "住", "注", "助", "著", "祝"],
    "gong": ["工", "公", "共", "功", "攻", "供"],
    "fa": ["发", "法", "罚"],
    "tou": ["头", "投", "透"],
    "shen": ["身", "深", "什", "神", "审"],
    "bai": ["百", "白", "败", "摆"],
    "qian": ["前", "钱", "千", "欠", "签", "迁"],
    "hou": ["后", "候", "厚"],
    "bei": ["被", "北", "备", "背", "杯", "悲"],
    "nan": ["南", "男", "难"],
    "wang": ["王", "往", "网", "忘", "望", "亡"],
    "fei": ["飞", "非", "费"],
    "lao": ["老", "劳"],
    "mian": ["面", "免", "棉", "眠"],
    "pi": ["批", "皮", "屁"],
    "dui": ["对", "队", "堆"],
    "zheng": ["正", "整", "政", "证", "争"],
    "zhao": ["找", "照", "赵", "招"],
    "yuan": ["元", "原", "远", "愿", "院", "员", "园"],
    "ma": ["吗", "马", "妈", "麻", "码"],
    "wen": ["问", "文", "闻", "稳"],
    "zhuan": ["转", "专", "赚"],
    "pian": ["片", "篇", "骗"],
    "rang": ["让"],
    "gei": ["给"],
    "dang": ["当", "党"],
    "cong": ["从", "聪"],
    "ling": ["另", "领", "零", "灵", "令"],
    "yang": ["样", "养", "阳", "洋", "杨"],
    "bian": ["变", "边", "便", "遍", "编"],
    "jie": ["接", "界", "解", "姐", "节", "结", "借"],
    "ying": ["应", "影", "英", "硬", "营"],
    "cai": ["才", "采", "彩", "菜", "材", "财"],
    "ku": ["苦", "哭", "库", "酷"],
    "zhan": ["站", "战", "展", "占"],
    "su": ["速", "苏", "素", "诉"],
    "suan": ["算", "酸"],
    "hu": ["互", "护", "湖", "户", "虎"],
    "se": ["色", "塞"],
    "an": ["安", "按", "暗", "案"],
    "cheng": ["成", "城", "程", "称", "承", "诚"],
    "feng": ["风", "封", "峰", "疯", "丰"],
    "peng": ["朋", "碰"],
    "chao": ["超", "朝", "潮", "炒"],
    "qing": ["轻", "清", "青", "请", "情"],
    "shao": ["少", "烧", "绍"],
    "jie": ["结", "节", "接", "姐", "解", "借", "界"],
    "jue": ["觉", "决", "绝", "脚"],
    "gua": ["挂", "瓜", "刮", "寡"],
    "ting": ["听", "停", "庭", "厅"],

    # 双字高频词
    "women": ["我们"],
    "nimen": ["你们"],
    "tamen": ["他们", "她们"],
    "dajia": ["大家"],
    "zij": ["自己"],
    "zhidao": ["知道"],
    "xihuan": ["喜欢"],
    "juede": ["觉得"],
    "yinggai": ["应该"],
    "keshi": ["可是"],
    "suoyi": ["所以"],
    "yinwei": ["因为"],
    "ruguo": ["如果"],
    "ranhou": ["然后"],
    "suiran": ["虽然"],
    "danshi": ["但是"],
    "buguo": ["不过"],
    "haishi": ["还是"],
    "huozhe": ["或者"],
    "bingqie": ["并且"],
    "yijing": ["已经"],
    "keyi": ["可以"],
    "xuyao": ["需要"],
    "zhishi": ["只是", "知识"],
    "keneng": ["可能"],
    "bixu": ["必须"],
    "meiyou": ["没有"],
    "zenme": ["怎么"],
    "shenme": ["什么"],
    "weishenme": ["为什么"],
    "zenmeyang": ["怎么样"],
    "duoshao": ["多少"],
    "zenyang": ["怎样"],
    "nali": ["那里", "哪里"],
    "zheli": ["这里"],
    "xianzai": ["现在"],
    "yihou": ["以后"],
    "yiqian": ["以前"],
    "jintian": ["今天"],
    "mingtian": ["明天"],
    "zuotian": ["昨天"],
    "shijian": ["时间"],
    "difang": ["地方"],
    "dongxi": ["东西"],
    "pengyou": ["朋友"],
    "haizi": ["孩子"],
    "xiansheng": ["先生"],
    "nvshi": ["女士"],
    "laoshi": ["老师"],
    "tongxue": ["同学"],
    "gongsi": ["公司"],
    "xuexiao": ["学校"],
    "yiyuan": ["医院"],
    "dianhua": ["电话"],
    "shouji": ["手机"],
    "diannao": ["电脑"],
    "wangluo": ["网络"],
    "xinxi": ["信息"],
    "wenti": ["问题"],
    "fangfa": ["方法"],
    "yuanyin": ["原因"],
    "jieguo": ["结果"],
    "qingkuang": ["情况"],
    "shenghuo": ["生活"],
    "gongzuo": ["工作"],
    "xuexi": ["学习"],
    "yundong": ["运动"],
    "yinyue": ["音乐"],
    "dianying": ["电影"],
    "shijie": ["世界"],
    "zhongguo": ["中国"],
    "meiguo": ["美国"],
    "riben": ["日本"],
    "beijin": ["北京"],
    "shanghai": ["上海"],
    "shehui": ["社会"],
    "zhengfu": ["政府"],
    "jingji": ["经济"],
    "fazhan": ["发展"],
    "huanjing": ["环境"],
    "lishi": ["历史"],
    "wenhua": ["文化"],
    "jiaoyu": ["教育"],
    "kexue": ["科学"],
    "jishu": ["技术"],
    "yanjiu": ["研究"],
    "guanxi": ["关系"],
    "fangshi": ["方式"],
    "sixiang": ["思想"],
    "taidu": ["态度"],
    "biaozhun": ["标准"],
    "jichu": ["基础"],
    "tiaojian": ["条件"],
    "nengli": ["能力"],
    "jihui": ["机会"],
    "fangxiang": ["方向"],
    "mubiao": ["目标"],
    "jihua": ["计划"],
    "huodong": ["活动"],
    "fuwu": ["服务"],
    "chanpin": ["产品"],
    "zhiliang": ["质量"],
    "anquan": ["安全"],

    # 三字及以上高频词
    "woxiangni": ["我想你"],
    "woaini": ["我爱你"],
    "xiexieni": ["谢谢你"],
    "duibuqi": ["对不起"],
    "meiguanxi": ["没关系"],
    "zaijian": ["再见"],
    "wanan": ["晚安"],
    "nihao": ["你好"],
    "zaoshanghao": ["早上好"],
    "xiawuhao": ["下午好"],
    "wanshanghao": ["晚上好"],
    "nihaoma": ["你好吗"],
    "hengaoxing": ["很高兴"],
    "renshini": ["认识你"],
    "bukeqi": ["不客气"],
    "meishier": ["没事儿"],
    "wusuowei": ["无所谓"],
    "yihuier": ["一会儿"],
    "youyisi": ["有意思"],
    "meiyisi": ["没意思"],
    "weishenme": ["为什么"],
    "zenmeyang": ["怎么样"],
    "chabuduo": ["差不多"],
    "diyici": ["第一次"],
    "shijishang": ["实际上"],
    "jibenshang": ["基本上"],
    "daduoshu": ["大多数"],
    "wulunruhe": ["无论如何"],
}
